### PR TITLE
[enh] add SMD Shielding Cabinets from Würth

### PR DESCRIPTION
**Pull request by pointhi**
http://katalog.we-online.de/en/pbs/WE-SHC#vs_ct:2

wuerth_smd

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @pointhi, can you add silkscreen around the cabinets as you have for https://github.com/KiCad/Shielding_Cabinets.pretty/pull/1? Otherwise looks great

**Comment by SchrodingersGat** [comment]
I've been looking for somewhere to put PCB shielding, too :)

**Comment by pointhi** [comment]
done

Now I used my new smd_shielding.py script, which simply only needs a definition file:
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Shielding/wuerth_smd_shielding.kicad_mod.yaml

**Comment by SchrodingersGat** [comment]
Thanks @pointhi

**Pull request merged**
